`self`は自分自身を返すオブジェクトです。使われる場所によって返す値が異なります。  
クラス内で使用される場合はそのクラスを、メソッド内で使用される場合はそのメソッドを実行するオブジェクト(レシーバ)を返します。  
問題では、メソッド`foo`が「実行されるオブジェクト`1`」 + `2`を返しています。  
メソッド`foo`が実行されるオブジェクトは`1`なので、メソッド`foo`内の`self`は`1`になります。

```ruby
class Foo
  self # => <Foo:0x00007ff58e1d7690> 自身を返す
end

def to_upcase
    self.upcase
end

"a".to_upcase # => "A"
```